# This is a basic workflow to help you get started with Actions

name: GitHub CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: npm install
      
  unit-test-client:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Frontend Unit Tests
      run: npm run test:unit:client
      
  unit-test-server:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker://circleci/node:10.15.3-browsers

    - name: Backend Unit Tests
      env:
        NODE_ENV: test
      run: npm run test:unit:server
      
  e2e-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker://mongo:3.6
    - uses: docker://circleci/node:10.15.3-browsers

    - name: E2E Tests
      env: 
        NODE_ENV: production
      run: npm run test:e2e
        
  heroku-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker://tmaier/dpl

    - name: Deploy to Heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
        
      run: dpl --provider=heroku --app=${{ secrets.HEROKU_APP_NAME }} --api-key=${{ secrets.HEROKU_API_KEY }}
